### PR TITLE
Add support of recursive reducerMap in handleActions

### PR DESCRIPTION
**Pull request by victordidenko**
`reducerMap` in `handleActions ` could have recursive structure, like

```
export default handleActions({
  [loginRoutine]: {
    SUCCESS: (state) => { ...state },
    FAILURE: (state) => { ...state }
  }
})
```
But doing so is impossible, because `loginRoutine.toString()` returns not PREFIX, but PREFIX/TRIGGER.

This pull request fixes this.

### CODE REVIEW

**Comment by victordidenko** [comment]
@afitiskin do you have any objections / proposals / notes here?

**Comment by afitiskin** [comment]
Problem here is that routine by itself is a trigger action creator:
```javascript
const routine = createRoutine('SOME');
const payload = { any: 'payload' };

expect(routine.toString()).to.deep.equal(routine.trigger.toString());
expect(routine(payload)).to.deep.equal(routine.trigger(payload));
```

After your changes we will have following:
```javascript
const routine = createRoutine('SOME');
const payload = { any: 'payload' };

console.log(routine.toString()); // SOME
console.log(routine(payload)); // { type: 'SOME/TRIGGER', payload: { any: 'payload' } };
```

So, it is inconsistent. We have two options:
1. Leave it as is at the moment
2. Change routine root from trigger action creator to something else.

What do you think?

**Comment by victordidenko** [comment]
I think this could be question of documentation :)
We could change meaning of routine itself, that routine by itself not is a trigger action creator, _but calls trigger action creator_.

I agree, that in some cases this might be a breaking change.

But the only place where you depend on string name of action -- is reducer. So, this change only restricts users to write explicitly `[routine.TRIGGER]: ...` instead of just `[routine]: ...` (if anyone writes so).

**Comment by afitiskin** [comment]
Ok, we need to update README as well before merging this.

**Comment by afitiskin** [comment]
By the way, what if we add `routine.PREFIX` constant, that will equal to routine prefix, so usage of handleActions will be as easy as:
```javascript
export default handleActions({
  [loginRoutine.PREFIX]: {
    SUCCESS: (state) => { ...state },
    FAILURE: (state) => { ...state }
  }
})
```
without any other changes into package. What do you think?

**Comment by victordidenko** [comment]
Hm... That's interesting workaround, I didn't think about it.

On the one hand, it is nice solution, without breaking changes, and without changing routine itself.

On the other hand, this constant looks like one more action type, `loginRoutine.SUCCESS`, `loginRoutine.FAILURE`, `loginRoutine.PREFIX`...

Also, I'm thinking about one PR (not yet starts to implement though), that will allow to change basic routine stages (like you mentioned in issue #20), and this constant `PREFIX` could theoretically conflicts with new stage name (doubtflully that one will want to add such stage name, but nonetheless).

So, honestly, I don't know...

**Comment by afitiskin** [comment]
Ok, your idea is good, so I think I found the best solution. In your PR we are implicitly using `routine.toString()` to get the prefix, why not to add and use `routine.getPrefix()`?

**Comment by victordidenko** [comment]
One thing that bugs me yet, sorry :)

After new release of `redux-actions` will be drafted, it will contain implementation for prefix option in `createActions` ( as described here → https://github.com/redux-utilities/redux-actions/issues/263 and merged PR is here → https://github.com/redux-utilities/redux-actions/pull/265 )

And when I'll finally have time to make PR for createRoutines here, I want to add this option too.

So, `.getPrefix()` will lead to inconsistency in names, one prefix in options and another prefix in routine name...

Maybe `.getName()` or `.getType()` in that case?

I don't like idea to call this function manually in handleActions, instead of implicit `.toString()`, but with saving backward compatibility this is the only choice, I guess...

**Comment by BohdanOther** [comment]
I've also wanted to use routines as reducer map keys
and wrote this simple utility, if someone interested

```
const typeDelimiter = '/';

const makeType = (prefix, type) => prefix.concat(type).join(typeDelimiter);

const extractType = (type) => {
    const sagaRoutineEnding = '/TRIGGER';
    if (type.endsWith(sagaRoutineEnding)) {
        return type.slice(0, -sagaRoutineEnding.length);
    }
    return type;
};

const iterator = (reducers = {}, initial = {}, prefix = []) => {
    const reducerTypes = Object.keys(reducers);

    return reducerTypes.reduce((acc, type) => {
        const reducer = reducers[type];

        return typeof (reducer) === 'function'
            ? ({
                ...acc,
                [makeType(prefix, type)]: reducer,
            })
            : iterator(
                reducer,
                acc,
                [makeType(prefix, extractType(type))]
            );
    }, initial);
};

export default function createReducer(reducerMap, initialState) {
    const flattened = iterator(reducerMap);

    return (state = initialState, action) => {
        const reducer = flattened[action.type];
        return reducer ? reducer(state, action.payload) : state;
    };
}
```

**Comment by afitiskin** [comment]
Now routine exposes `routine._PREFIX`

**Pull request closed without merging**
