### PR TITLE
Add typescript definition file.

### PR DESCRIPTION
**Pull request by janstrohbeck**
I use this package in a typescript project, so I created a definition file for the typescript compiler. It would be great if this could be packaged with the library.

### CODE REVIEW

**Comment by afitiskin** [comment]
@janstrohbeck First of all, thank you! Sorry for a delay, I was working on version 2.0. It was a big update, I totally reworked the module. If you have time, please check new version. It will be great if you add definition file for a new version. Thank you!

**Comment by janstrohbeck** [comment]
I've updated the definition file for v2. It's probably not perfect, but worked so far in my case. Please note that this commit adds a new dependency for the definition file of redux-actions, as I used their types in this definition file.

**Comment by afitiskin** [comment]
@janstrohbeck As I see, types for `redux-actions` are in separate package, may be we should do the same way?

**Comment by janstrohbeck** [comment]
Yes, they are on https://github.com/DefinitelyTyped/DefinitelyTyped, which is also an option. It's recommended to bundle the type definitions with the corresponding package though, if possible:
http://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html

**Comment by afitiskin** [comment]
@janstrohbeck merged and published as `2.1.0`

**Pull request merged**
